name: CMake CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        type: ['edge', 'win']

    steps:
      - uses: actions/checkout@v2

      - name: Cache CMake
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}-${{ matrix.type }}

      - name: Get Windows SDK
        run: |
          $url = "${{ github.workspace }}/winsdktemp/winsdksetup.exe"
          mkdir ${{ github.workspace }}/winsdktemp
          $client = New-Object System.Net.WebClient
          $client.DownloadFile("https://go.microsoft.com/fwlink/p/?linkid=2120843", $url)
          Start-Process -Wait $url "/features OptionId.UWPCpp /q"

      - name: Get WebView2 Runtime
        if: ${{ matrix.type == 'edge' }}
        run: |
          $url = "${{ github.workspace }}/webview2/MicrosoftEdgeWebview2Setup.exe"
          mkdir ${{ github.workspace }}/webview2
          $client = New-Object System.Net.WebClient
          $client.DownloadFile("https://go.microsoft.com/fwlink/p/?LinkId=2124703", $url)
          Start-Process -Wait $url "/silent /install"

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DWEBVIEW_USE_EDGE=${{ matrix.type == 'edge' && 'ON' || 'OFF' }} test

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        if: ${{ matrix.type == 'edge' }}
        run: |
          $PYTHON3_PROC = Start-Process -NoNewWindow -PassThru python3 -ArgumentList '-m', 'http.server', '8080'
          ctest -C ${{env.BUILD_TYPE}} --timeout 5
          Stop-Process $PYTHON3_PROC.Id

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache CMake
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} test

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          python3 -m http.server 8080 &
          PYTHON3_PID=$!
          ctest -C ${{env.BUILD_TYPE}} --timeout 5
          kill $PYTHON3_PID

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev xvfb -y

      - name: Cache CMake
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} test

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          python3 -m http.server 8080 &
          PYTHON3_PID=$!
          xvfb-run ctest -C ${{env.BUILD_TYPE}} --timeout 5
          kill $PYTHON3_PID
